stages:
  - "build"
  - "deploy"

image: alpine

build:
  stage: build
  script:
    - docker build -t emreyokur/hello-goose .
    - docker push emreyokur/hello-goose

deploy:
  stage: deploy
  script: 
    - kubectl apply -f kubernetes/deployment.yml -n hello-goose
    - kubectl apply -f kubernetes/service.yml -n hello-goose
