stages:
  - "build"
  - "deploy"

image: alpine

build:
  before_script:
    - git clean -fd
  tags:
    - docker
  stage: build
  script:
    - docker login -u emreyokur -p b5dc4d49-d771-4a21-a641-be4e81a36fb2
    - docker build -t emreyokur/hello-goose .
    - docker push emreyokur/hello-goose

deploy:
  tags:
    - kubectl
  stage: deploy
  script: 
    - kubectl apply -f kubernetes/deployment.yml -n hello-goose
    - kubectl apply -f kubernetes/service.yml -n hello-goose
