stages:
  - "build"
  - "deploy"

image: alpine

build:
  tags:
    - docker
  stage: build
  script:
    - docker login -u emreyokur -p $DOCKER_PASS
    - docker build -t emreyokur/hello-goose .
    - docker push emreyokur/hello-goose

deploy:
  tags:
    - kubectl
  stage: deploy
  script: 
    - kubectl apply -f kubernetes/deployment.yml -n hello-goose
    - kubectl apply -f kubernetes/service.yml -n hello-goose
