stages:
  - "build"
  - "deploy"

image: paketobuildpacks/builder

build:
  stage: build
  script:
    - /cnb/lifecycle/creator -app=. emreyokur/hello-goose:latest
    - docker push emreyokur/hello-goose

deploy:
  stage: deploy
  script: 
    - kubectl apply -f kubernetes/deployment.yml
    - kubectl apply -f kubernetes/service.yml
