stages:
  - "build"
  - "deploy"

image: paketobuildpacks/builder

variables:
  REGISTRY_GROUP_PROJECT: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

build:
  stage: build
  script:
    - cnb/lifecycle/creator -app=. $REGISTRY_GROUP_PROJECT:latest

deploy:
  stage: deploy
  script: 
    - kubectl apply -f kubernetes/deployment.yml
    - kubectl apply -f kubernetes/service.yml